---

test_name: Retrieve a payment resource

stages:
  - name: Retrieve a single payment resource
    request:
      url: http://127.0.0.1:8080/payments/1
      method: GET
    response:
      status_code: 200
      body:
        status: "ok"
        data:
          id: 1
          beneficiary: 123
          debtor: 122
          amount: 100
          currency: "GBP"

---

test_name: Retrieving a non-existent payment resource fails

stages:
  - name: Attempt to retrieve a non-existent resource
    request:
      url: http://127.0.0.1:8080/payments/2
      method: GET
    response:
      status_code: 404
      body:
        status: "not found"

---

test_name: Retrieving an invalid payment resource ID emits an error

stages:
  - name: Attempt to retrieve an invalid payment resource ID
    request:
      url: http://127.0.0.1:8080/payments/foobar
      method: GET
    response:
      status_code: 401
      body:
        status: "error"
        error_info: "Invalid payment resource ID"
